### ISSUE TITLE
作為公開服務好不好，再加上些什麼功能好呢？

### ISSUE THREAD

**Issue by dinowang** [dinowang/pointer-as-a-service#1]
作為公開服務好不好，再加上些什麼功能好呢？

如果辦得到有可能會做喔 (twMVC #34 後關閉調查)

**Comment by wujpkimo** [comment]
加個黑屛選項吧

**Comment by kkbruce** [comment]
It's good idea.

**Comment by dinowang** [comment]
黑色的 theme 已經加上去，在有專業設計師加入前應該可以擋一下子

![Themes](https://user-images.githubusercontent.com/3980212/52940911-993ad900-33a2-11e9-8f36-fa4ee81d1e1f.png)
