### ISSUE TITLE
[提案]使用VirtualJoystick套件或相關方法控制PPT

### ISSUE THREAD

**Issue by ShangWeiWayne** [dinowang/pointer-as-a-service#5]
VirtualJoystick.js是一款在網頁上模擬遊戲搖桿的js套件
可以加強使用者體驗
http://jeromeetienne.github.io/virtualjoystick.js/examples/basic.html

相關套件還有nipplejs
https://yoannmoinet.github.io/nipplejs/

**Comment by dinowang** [comment]
是個不錯的主意，加入手機版改版設計考量

**Comment by dinowang** [comment]
不難加，所以先加上去了，大改版前先使用 NippleJS 看看效果

![image](https://user-images.githubusercontent.com/3980212/52996328-3dcb2280-3458-11e9-9364-b6c2b2c395bc.png)
